server:
  port: 8080

spring:
  application:
    name: spring-cloud-gateway-ratelimiter

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    org.springframework.cloud.gateway: DEBUG

cloud:
  gateway:
    routes:
      - id: route1
        uri: https://httpbin.org
        predicates:
          - Path=/tokenbucket/**
        filters:
          - name: CustomRateLimiter
            args:
              routeId: route1

      - id: route2
        uri: https://httpbin.org
        predicates:
          - Path=/leakybucket/**
        filters:
          - name: CustomRateLimiter
            args:
              routeId: route2
