spring:
  application:
    name: rate-limiter-gateway

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

logging:
  level:
    org.springframework.cloud.gateway: DEBUG

cloud:
  gateway:
    routes:
      - id: route1
        uri: https://httpbin.org
        predicates:
          - Path=/tokenbucket/**
        filters:
          - name: CustomRateLimiter
            args:
              routeId: route1

      - id: route2
        uri: https://httpbin.org
        predicates:
          - Path=/leakybucket/**
        filters:
          - name: CustomRateLimiter
            args:
              routeId: route2